[build-system]
requires = ["setuptools", "wheel"] 
build_backend = "setuptools.build_meta"
[project]
name = "pyndg" 
version = "0.1.0" 
description = "A high-order nodal discontinuous Galerkin finite element library with AD."
authors = [{name = "Matteo Caldana", email = "matteo.caldana@polimi.it"}]
requires-python = ">=3.12"
dependencies = ["numpy", "jax", "matplotlib", "gmsh==4.15.2", "scipy", "scikit-sparse>=0.5.0"]
[project.optional-dependencies]
dev = ["pytest", "black"]

[tool.setuptools.packages.find]
where = ["src"]
